// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package cn.ngtoken.grpc.service;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ngtoken.grpc.service.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
