// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package cn.ngtoken.grpc.service;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ngtoken_grpc_service_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ngtoken_grpc_service_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ngtoken_grpc_service_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ngtoken_grpc_service_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\027cn.ngtoken.grpc.service\"(\n" +
      "\013UserRequest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"" +
      "\037\n\014UserResponse\022\017\n\007message\030\001 \001(\t2h\n\013User" +
      "Service\022Y\n\010listUser\022$.cn.ngtoken.grpc.se" +
      "rvice.UserRequest\032%.cn.ngtoken.grpc.serv" +
      "ice.UserResponse\"\000B\024B\020UserServiceProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_ngtoken_grpc_service_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ngtoken_grpc_service_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ngtoken_grpc_service_UserRequest_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_cn_ngtoken_grpc_service_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ngtoken_grpc_service_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ngtoken_grpc_service_UserResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
