// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package cn.ngtoken.grpc.service;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ngtoken.grpc.service.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
